name: install
description: install node_modules
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: npm
    - uses: actions/cache@v3
      id: cache
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
        restore-keys: ${{ runner.os }}-build-
    - uses: actions/cache@v3
      id: cache-style-system
      env:
        cache-name: cache-style-system
      with:
        path: style-system
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('panda.config.ts', 'postcss.config.cjs') }}
        restore-keys: ${{ runner.os }}-build-
    - if: ${{ steps.cache.outputs.cache-hit != 'true' || steps.cache-style-system.outputs.cache-hit != 'true' }}
      run: npm ci
      shell: bash
